# Generated by Django 3.0.1 on 2019-12-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jtitle", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
