# Generated by Django 3.0.1 on 2020-07-09 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_clientjobs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientjobs',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='clientjobs',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
