version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_volume/:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: django
      POSTGRES_DB: testdb
    container_name: test_postgres