# Generated by Django 3.0.1 on 2020-07-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricamodel',
            options={'ordering': ['-time']},
        ),
    ]
