# Generated by Django 3.2.13 on 2022-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prica', '0002_auto_20200709_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricamodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
