# Generated by Django 3.0.1 on 2019-12-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=20)),
                ('blog_date', models.DateTimeField()),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_description', models.TextField()),
            ],
        ),
    ]
