# Generated by Django 3.0.1 on 2020-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
