# Generated by Django 4.0.4 on 2022-04-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_cover"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cover",
        ),
    ]
